### ISSUE TITLE
Build fail

### ISSUE THREAD

**Issue by omangSunday** [Nozbe/WatermelonDB#1268]
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':nozbe_watermelondb:compileDebugKotlin'.
> Compilation error. See log for more details

**Comment by Boztown** [comment]
In `android/build.gradle`:

```
// Top-level build file where you can add configuration options common to all sub-projects/modules.
buildscript {
    ext {
        kotlinVersion = '1.3.50'
```

Make sure you have the Kotlin version set like this. It's mentioned here: https://nozbe.github.io/WatermelonDB/Installation.html#android-react-native

I assumed, given a brand new RN project, that I'd probably have the correct version set. I didn't, got the same error as you here, and following this instruction fixed it.

**Comment by KrisLau** [comment]
@Boztown @radex When I upgrade my `kotlinVersion` from `1.5.0` to `1.7.10` I get 
```
Execution failed for task ':nozbe_watermelondb:compileDebugKotlin'.
> A failure occurred while executing org.jetbrains.kotlin.compilerRunner.GradleCompilerRunnerWithWorkers$GradleKotlinCompilerWorkAction
   > Compilation error. See log for more details
```

**Comment by radex** [comment]
should be fixed in the latest version

**Comment by slandrei** [comment]
Right no it failed for me too with  "@nozbe/watermelondb": "^0.25.5"

LOG:
------------------------------------------ 
The binary version of its metadata is 1.6.0, expected version is 1.1.15.
Execution failed for task ':nozbe_watermelondb:compileDebugKotlin'.
--------------------------------------------

**Comment by lekbit** [comment]
> @Boztown @radex When I upgrade my `kotlinVersion` from `1.5.0` to `1.7.10` I get
> but it works with `1.6.21`

Confirm version change to `ext.kotlinVersion = '1.6.21'` solves the error
